### ISSUE TITLE
Registration form fields validation

### ISSUE THREAD

**Issue by c1vian00** [DIN-Project-Team-4/cinescope-backend#2]
As a user, I want to sign up by providing my e-mail and my password, so I can create an account.

Add frontend and backend validation:

- E-mail field only accepts valid e-mail addresses (must contain @)
- Password field requires at least a capital letter, a number and must be at least 6 characters long

**Comment by t3inli00** [comment]
need to do validation part... after getting confirmed with the group.. have to do the validation
