### ISSUE TITLE
Movie review tests

### ISSUE THREAD

**Issue by c1vian00** [DIN-Project-Team-4/cinescope-backend#26]
As a registered user, I want to create movie reviews.

Create test scenarios:
- Movie review creation works when a registered user writes a correctly formatted review.
- Movie review creation shows error, if the created movie review isn't formatted correctly.
- Movie review editing and deletion work when the writer of the review wants to edit their own review
- Movie review editing and deletion show error, if a registered user wants to edit/delete someone else's review.

**Comment by t3inli00** [comment]
fine tunes are done
